### ISSUE TITLE
Week 3 Feedback

### ISSUE THREAD

**Issue by dtaylo95** [Hoytx/qbb2023-answers#4]
**Python script that performs alignment based on user input** 

**7.75/8**

| Exercise | Points Possible | Grade |
| -------- | ------- | ------- |
| Read in inputs | 2 | 2 | 
| Initialize matrices | 1 | 1 | 
| Populate matrices | 2 | 2 | 
| Perform traceback | 2 |  1.75 | 
| Write alignment to file | 0.5 | 0.5 | 
| Print out alignment score and number of gaps in each sequence | 0.5 | 0.5 | 

**DNA alignment file** 

**0.5/0.5**

**AA alignment file** 

**0.5/0.5**

**`README.md` with alignment score and number of gaps in each sequence for each alignment**

**1/1**

Total: **9.75/10**

Nice work! I think you have a minor issue in your traceback in that you're actually starting in the cell up and left of the bottom right, rather than the bottom right itself. This means you're leaving off the last base of both sequences,  which also impacts your alignment score and count of gaps.

For full credit, you just need to fix this minor issue.

**Comment by Hoytx** [comment]
I made the change to the code and reran the script for both AA and DNA. The issue should be fixed, I updated the readme file with the new alignment scores.

**Comment by dtaylo95** [comment]
One more minor issue that I missed earlier: check your `while` loop condition. What happens if if `i` and `j` don't reach 0 at the same time (i.e. if you had leading gaps)?<br>https://github.com/Hoytx/qbb2023-answers/blob/93d78fbb2d93a99ce9c2c9fc2dfa25bf2439db75/week3/homework.py#L67

**Comment by Hoytx** [comment]
It would halt early in that case, replacing AND with OR should fix this problem as it would continue the loop until both i and j are = 0.

**Comment by dtaylo95** [comment]
Great! Your grade has been updated to a 10/10.

If you don't have any other questions, you can close this issue, just so you know you're done working on this assignment.
